### ISSUE TITLE
Current version (0.7.8) missing from releases on GitHub

### ISSUE THREAD

**Issue by rsinnet** [vcstools/rosinstall#115]
Looking at the releases on GitHub for this repo, I see 0.7.7 released years ago but I don't see the version that installs through apt which is 0.7.8. Should the release be tagged?

**Comment by wjwwood** [comment]
Looks like @tfoote made that release, it's possible he just forgot to push the tag.

https://github.com/vcstools/rosinstall/commit/6e85b564d7d59ecdffc1d2e9e6b595952ffde75b

**Comment by wjwwood** [comment]
I just created it https://github.com/vcstools/rosinstall/releases/tag/0.7.8, thanks for pointing it out.
