### ISSUE TITLE
new dropin element for .rosinstall files

### ISSUE THREAD

**Issue by tkruse** [vcstools/rosinstall#35]
Currently rosws allows "other" elements which will only be added to the ROS_PACKAGE_PATH by the setup.sh rosws / rosinstall generates. These elements have no function in catkin (using wstool).

Catkin allows drop-in semantics by default, meaning users are free to git clone catkin packages into their source space, and catkin will build them. With rosws+rosbuild, this behavior only works in sandbox folders, in which no VCS operations happen.

In https://github.com/vcstools/vcstools/issues/27 I explored the idea of going less stateful, but the idea there is undesirable in my opinion for the reasons given there.

So another idea is to introduce a new rosnstall syntax element "dropin", which in rosws also adds the folder to the ROS_PACKAGE_PATH, but also performs default scm operations the way Dirk suggests for a generic vcstool command.

This would allow in catkin to define dropin folders where people can clone into, getting both catkin immediate build as well as immediate support for vcs operations via wstool.

The semantics would have to be slightly different for git than for the other SCMs, because
git co tag123
git update
remains at tag123, whereas similar operations for svn, hg and bzr would on the second call move away from that revision, if possible.

A Caveat here is that for catkin, this features does not fully provide what Dirk imagines, being able to create a nice workspace layout via native SCM operations and then export that layout to a .rosinstall file (assuming the additional hierarchy of a dropin subfolder is not "nice"). However we could make sure that if a user insists, we allow "." as a valid value for the dropin element, making the whole workspace a drop-in folder for vcs operations.

There are some other corner cases with difficulties, such as folders having multiple scm folders, where I would suggest just creating a warning.

Also given the choice of making the whole workspace folder a dropin folder, some users may want a feature to exclude subfolders from vcs operations, just like the CATKIN_IGNORE file. So to mirror that we could have a WSTOOL_IGNORE file support as well, for dropin folders.

Changing the behavior of the "other" element to also perform vcs operations with default semantics on any scm subfolder is probably not a good idea.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #126.
