### ISSUE TITLE
Add support for wildcards to rosws update

### ISSUE THREAD

**Issue by tfoote** [vcstools/rosinstall#4]
https://kforge.ros.org/vcstools/trac/ticket/67

It would be cool to have wildcards in rosws up, e.g.:
rosws update 'cram*'
Tully, what do you think?

Created attached patch, won't push until Tully gives okay for this. (note trac email notification still do not work for me, or Lorenz)
Changed 7 days ago by kruset

attachment wildcards.patch   added
comment:2 Changed 7 days ago by tfoote

I'm a little worried about this possibly being a problem in the future. If you don't quote it the base completion will do similar things. 
I tested and svn doesn't do this. Does git or hg support wildcard syntax?
comment:3 Changed 6 days ago by moesenle

I don't think version control systems provide wildcard syntax. I guess they rely on the shell's glob expansion which course works for rosws, too. But rosws can be invoked basically everywhere and infers the workspace from the ROS_WORKSPACE variable. Wildcard support is just pure convenience but I felt like it would help me in my everyday workflow :)

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #126.
