### ISSUE TITLE
prompt_merge refactor

### ISSUE THREAD

**Issue by tkruse** [vcstools/rosinstall#50]
Note to myself:
code in multiproject_cli.prompt_merge() should be improved by avoiding to construct a new config element on each interaction with the user. This was done mostly to avoid deep-copy of the original config element.

One consequence is that currently we read the same yaml from a web location in every iteration. As users probably don't use the extended features of merges very often this has low priority.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #126.
