### ISSUE TITLE
introduce include elements

### ISSUE THREAD

**Issue by tfoote** [vcstools/rosinstall#6]
https://kforge.ros.org/vcstools/trac/ticket/8

from  http://code.ros.org/lurker/message/20111023.065813.7841f236.gl.html
The change introduces "- include" elements for rosinstall files requiring a URI. A rosinstall file at that location will re read and used as if the elements were in place of the include. The resulting rosinstall file will still only have the "include" element, so no merge with the referenced .rosinstall file happens.
No command-line option exists for this use case, this can only be achieved by manually changing the .rosinstall or merging with a rosinstall having .include elements.
--- a/scripts/rosinstall
+++ b/scripts/rosinstall
@@ -230,17 +230,19 @@ class Config:

```
     # Get the version and source_uri elements
     source_uri = v.get('uri', None)
     version = v.get('version', '')

     #compute the local_path for the config element
     local_path = os.path.normpath(os.path.join(self.base_path, local_name))
```
-        if k == 'other':
-        if k == 'include':
-          self.load_yaml(rosinstall.helpers.get_yaml_from_uri(source_uri),rosinstall_source_uri)
-        elif k == 'other':

Changed 10 months ago by kruset

Comment:
Maybe the local-name could be used as a subfolder rather than being ignored when given.
Two other robustness issues are likely:
1) Prevent infinite recursion, as you can use a local filename as URI (though infinite recursions are already possible with rosinstall as it is, e.g. "$ rosinstall . . .")
2) Rewriting, when you merge a rosinstall file into your current environment. I think it might only be necessary to extend the list in def rewrite_included_source(source_yaml, source_path):
There also is a small usability issue on having multiple ros distros configured in the current environment, rosinstall neither checks nor prevents that. And this is more likely to occur than now when an included remote rosinstall file was changed.
The difference between merging with a rosinstall file and including it could become confusing for new rosinstall users. But personally I never liked merging of rosinstall files much. (Especially the peculiarity that when pointing to a local directory in "$ rosinstall . /path/to/local/dir", and there was a .rosinstall there, the entries would be merged as "other" elements.)
Last edited 10 months ago by kruset (previous) (diff)
comment:2 Changed 10 months ago by kruset

 def rewrite_included_source(source_yaml, source_path):
   #print "before", source_yaml
   for entry in source_yaml:
-    types = ['svn', 'bzr', 'hg', 'git', 'other']
-    types = ['svn', 'bzr', 'hg', 'git', 'other', 'include']
  For better or worse, the change above causes "include" snippets in ".rosinstall" files in directories to merge with to be rewritten as "other" elements. Not sure what the consistent implementation would be.
  Maybe parsing the referenced rosinstall and including all its elements as "other" elements, recursive for "include" elements.
  Last edited 10 months ago by kruset (previous) (diff)
  comment:3 Changed 10 months ago by kruset

diff --git a/scripts/rosinstall b/scripts/rosinstall
--- a/scripts/rosinstall
+++ b/scripts/rosinstall
@@ -213,34 +213,38 @@ class Config:
       self.load_yaml(self.source, self.source_uri)
       self.valid = True
     else:
       self.valid = False

   def is_valid(self):
     return self.valid
-  def load_yaml(self, y, rosinstall_source_uri):
-  def load_yaml(self, y, rosinstall_source_uri, prefix_path = ''):
   for t in y:
     for k, v in t.iteritems():
  
  ```
   # Check that local_name exists and record it
   if not 'local-name' in v:
     raise ROSInstallException("local-name is required on all rosinstall elements")
   else:
     local_name = v['local-name']
  
   # Get the version and source_uri elements
   source_uri = v.get('uri', None)
   version = v.get('version', '')
  
   #compute the local_path for the config element
  ```
-        local_path = os.path.normpath(os.path.join(self.base_path, local_name))
- ```
     local_path = os.path.normpath(os.path.join(self.base_path, prefix_path, local_name))
  ```
- ```
     if k == 'other':
  ```
-        if k == 'include':
-          y = rosinstall.helpers.get_yaml_from_uri(source_uri)
-          if y != None:
-            self.load_yaml(y, rosinstall_source_uri, local_name)
-          else:
-            raise ROSInstallException("Failed to include uri %s" % source_uri)
-        elif k == 'other':
  this way local-name is being used as subfolder. local-name: "" also works. Also more robust against bad uris.
  Last edited 10 months ago by kruset (previous) (diff)
  comment:4 Changed 10 months ago by kruset

Also note --diff, ---status and --info (as per uncommited patch) seem to work fine with include elements so far.
comment:5 Changed 10 months ago by DanielStonier

A possible corner-case for subfolder usage - does it work with the electric bare-bones generated .rosinstall (specifically thinking of an include with the 'special' ros stack inside)?
include:
uri:  http://packages.ros.org/cgi-bin/gen_rosinstall.py?rosdistro=electric&variant=ros-base&overlay=no
local-name: bare-bones
comment:6 Changed 5 months ago by bit_pirate

Bump!
What's the status of this? Are there still open issues?
It would be really nice to have this feature.
comment:7 Changed 5 months ago by tfoote

In our recent restructuring there were several issues identified which could be a problem for this element. 
Consistency of storage is a bit of an issue, especially for use cases like the included file removes an element. This will likely need a non trivial extension to the file format.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #126.
