### ISSUE TITLE
debian packages lack bash completion

### ISSUE THREAD

**Issue by tkruse** [vcstools/rosinstall#76]
Currently the ri_bash_completion project on github provides shell scripts to create bash completion. Those should be included in the debians (might not even require separate packages). The pypi version of the completion might also be dropped.

For wstool adapting the script should be straightforward (e.g. removing regenrate command)

If you can tell me how to generate a debian package locally, I am happy to work on that.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #126.
